import { StudentAssessment } from "@/types/assessment";

// Mock high school assessment data for one semester (Grade 10 - Second Semester)
const mockHighSchoolAssessments: StudentAssessment[] = [
  {
    id: 1,
    teachingAssignmentId: 101,
    studentId: 1,
    practical1: 18,
    practical2: 16,
    practical3: 0,
    practical1Type: "Quiz",
    practical2Type: "Assignment",
    practical3Type: "Not Applicable",
    totalPractical: 34,
    practicalStatus: "COMPLETED",
    theory: 42,
    theoryStatus: "COMPLETED",
    totalMark: 76,
    gradeInLetter: "B",
    comment: "Good performance in mathematics",
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    teachingAssignment: {
      id: 101,
      teacherId: 1,
      sectionId: 1,
      courseId: 1,
      academicSemesterId: 2,
      academicYearId: 1,
      level: "10",
      departmentId: 1,
      teacher: {
        id: 1,
        userId: 1,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
      },
      section: {
        id: 1,
        sectionName: "10-A",
        academicYearId: 1,
        createdAt: "2024-01-01T00:00:00Z",
        departmentId: 1,
      },
      course: {
        id: 1,
        collegeId: 1,
        departmentId: 1,
        level: "10",
        courseCode: "MATH-10",
        title: "Mathematics",
        theoryNhrs: 3,
        practicalNhrs: 1,
        cooperativeNhrs: 0,
        totalNhrs: 4,
        createdAt: "2024-01-01T00:00:00Z",
      },
      academicSemester: {
        id: 2,
        name: "Second Semester",
        academicYearId: 1,
        startDate: "2025-02-01",
        endDate: "2025-06-30",
        registrationStartDate: "2025-01-15",
        registrationEndDate: "2025-02-15",
        createdAt: "2024-01-01T00:00:00Z",
      },
    },
    student: {
      id: 1,
      studentTempId: 1001,
      userId: 101,
      placeOfBirthTown: "Arba Minch",
      placeOfBirthZone: "Gamo",
      placeOfBirthRegion: "SNNPR",
      dateOfBirth: "2007-03-15",
      addressKebele: "01",
      addressWoreda: "Arba Minch Zuria",
      addressTown: "Arba Minch",
      addressZone: "Gamo",
      addressRegion: "SNNPR",
      phoneHome: "+251911234567",
      phoneOffice: "",
      maritalStatus: "Single",
      departmentId: 1,
      programId: 1,
      admissionTypeId: 1,
      listOfSlip: "2024/2025",
      registrationDate: "2024-09-01",
      profilePicture: null,
      currentStudyingYear: "2024",
      currentStudyingSemester: "Second Semester",
      currentStudyingLevel: "10",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-09-01T00:00:00Z",
      sectionId: 1,
      user: {
        id: 101,
        firstName: "Sarah",
        middleName: "Jane",
        lastName: "Johnson",
        email: "sarah.johnson@student.edu",
        phoneNumber: "+251911234567",
        password: "hashed_password",
        userType: "STUDENT",
        gender: "Female",
        nationality: "Ethiopian",
        userMainId: "GS/2024/001",
      },
    },
  },
  {
    id: 2,
    teachingAssignmentId: 102,
    studentId: 1,
    practical1: 16,
    practical2: 14,
    practical3: 0,
    practical1Type: "Lab Work",
    practical2Type: "Quiz",
    practical3Type: "Not Applicable",
    totalPractical: 30,
    practicalStatus: "COMPLETED",
    theory: 38,
    theoryStatus: "COMPLETED",
    totalMark: 68,
    gradeInLetter: "C+",
    comment: "Satisfactory understanding of physics concepts",
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    teachingAssignment: {
      id: 102,
      teacherId: 2,
      sectionId: 1,
      courseId: 2,
      academicSemesterId: 2,
      academicYearId: 1,
      level: "10",
      departmentId: 1,
      teacher: {
        id: 2,
        userId: 2,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
      },
      section: {
        id: 1,
        sectionName: "10-A",
        academicYearId: 1,
        createdAt: "2024-01-01T00:00:00Z",
        departmentId: 1,
      },
      course: {
        id: 2,
        collegeId: 1,
        departmentId: 1,
        level: "10",
        courseCode: "PHYS-10",
        title: "Physics",
        theoryNhrs: 2,
        practicalNhrs: 1,
        cooperativeNhrs: 0,
        totalNhrs: 3,
        createdAt: "2024-01-01T00:00:00Z",
      },
      academicSemester: {
        id: 2,
        name: "Second Semester",
        academicYearId: 1,
        startDate: "2025-02-01",
        endDate: "2025-06-30",
        registrationStartDate: "2025-01-15",
        registrationEndDate: "2025-02-15",
        createdAt: "2024-01-01T00:00:00Z",
      },
    },
    student: {
      id: 1,
      studentTempId: 1001,
      userId: 101,
      placeOfBirthTown: "Arba Minch",
      placeOfBirthZone: "Gamo",
      placeOfBirthRegion: "SNNPR",
      dateOfBirth: "2007-03-15",
      addressKebele: "01",
      addressWoreda: "Arba Minch Zuria",
      addressTown: "Arba Minch",
      addressZone: "Gamo",
      addressRegion: "SNNPR",
      phoneHome: "+251911234567",
      phoneOffice: "",
      maritalStatus: "Single",
      departmentId: 1,
      programId: 1,
      admissionTypeId: 1,
      listOfSlip: "2024/2025",
      registrationDate: "2024-09-01",
      profilePicture: null,
      currentStudyingYear: "2024",
      currentStudyingSemester: "Second Semester",
      currentStudyingLevel: "10",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-09-01T00:00:00Z",
      sectionId: 1,
      user: {
        id: 101,
        firstName: "Sarah",
        middleName: "Jane",
        lastName: "Johnson",
        email: "sarah.johnson@student.edu",
        phoneNumber: "+251911234567",
        password: "hashed_password",
        userType: "STUDENT",
        gender: "Female",
        nationality: "Ethiopian",
        userMainId: "GS/2024/001",
      },
    },
  },
  {
    id: 3,
    teachingAssignmentId: 103,
    studentId: 1,
    practical1: 17,
    practical2: 15,
    practical3: 0,
    practical1Type: "Lab Experiment",
    practical2Type: "Project",
    practical3Type: "Not Applicable",
    totalPractical: 32,
    practicalStatus: "COMPLETED",
    theory: 40,
    theoryStatus: "COMPLETED",
    totalMark: 72,
    gradeInLetter: "B-",
    comment: "Strong performance in chemistry practicals",
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    teachingAssignment: {
      id: 103,
      teacherId: 3,
      sectionId: 1,
      courseId: 3,
      academicSemesterId: 2,
      academicYearId: 1,
      level: "10",
      departmentId: 1,
      teacher: {
        id: 3,
        userId: 3,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
      },
      section: {
        id: 1,
        sectionName: "10-A",
        academicYearId: 1,
        createdAt: "2024-01-01T00:00:00Z",
        departmentId: 1,
      },
      course: {
        id: 3,
        collegeId: 1,
        departmentId: 1,
        level: "10",
        courseCode: "CHEM-10",
        title: "Chemistry",
        theoryNhrs: 2,
        practicalNhrs: 1,
        cooperativeNhrs: 0,
        totalNhrs: 3,
        createdAt: "2024-01-01T00:00:00Z",
      },
      academicSemester: {
        id: 2,
        name: "Second Semester",
        academicYearId: 1,
        startDate: "2025-02-01",
        endDate: "2025-06-30",
        registrationStartDate: "2025-01-15",
        registrationEndDate: "2025-02-15",
        createdAt: "2024-01-01T00:00:00Z",
      },
    },
    student: {
      id: 1,
      studentTempId: 1001,
      userId: 101,
      placeOfBirthTown: "Arba Minch",
      placeOfBirthZone: "Gamo",
      placeOfBirthRegion: "SNNPR",
      dateOfBirth: "2007-03-15",
      addressKebele: "01",
      addressWoreda: "Arba Minch Zuria",
      addressTown: "Arba Minch",
      addressZone: "Gamo",
      addressRegion: "SNNPR",
      phoneHome: "+251911234567",
      phoneOffice: "",
      maritalStatus: "Single",
      departmentId: 1,
      programId: 1,
      admissionTypeId: 1,
      listOfSlip: "2024/2025",
      registrationDate: "2024-09-01",
      profilePicture: null,
      currentStudyingYear: "2024",
      currentStudyingSemester: "Second Semester",
      currentStudyingLevel: "10",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-09-01T00:00:00Z",
      sectionId: 1,
      user: {
        id: 101,
        firstName: "Sarah",
        middleName: "Jane",
        lastName: "Johnson",
        email: "sarah.johnson@student.edu",
        phoneNumber: "+251911234567",
        password: "hashed_password",
        userType: "STUDENT",
        gender: "Female",
        nationality: "Ethiopian",
        userMainId: "GS/2024/001",
      },
    },
  },
  {
    id: 4,
    teachingAssignmentId: 104,
    studentId: 1,
    practical1: 19,
    practical2: 17,
    practical3: 0,
    practical1Type: "Lab Work",
    practical2Type: "Assignment",
    practical3Type: "Not Applicable",
    totalPractical: 36,
    practicalStatus: "COMPLETED",
    theory: 44,
    theoryStatus: "COMPLETED",
    totalMark: 80,
    gradeInLetter: "B+",
    comment: "Excellent grasp of biological concepts",
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    teachingAssignment: {
      id: 104,
      teacherId: 4,
      sectionId: 1,
      courseId: 4,
      academicSemesterId: 2,
      academicYearId: 1,
      level: "10",
      departmentId: 1,
      teacher: {
        id: 4,
        userId: 4,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
      },
      section: {
        id: 1,
        sectionName: "10-A",
        academicYearId: 1,
        createdAt: "2024-01-01T00:00:00Z",
        departmentId: 1,
      },
      course: {
        id: 4,
        collegeId: 1,
        departmentId: 1,
        level: "10",
        courseCode: "BIOL-10",
        title: "Biology",
        theoryNhrs: 2,
        practicalNhrs: 1,
        cooperativeNhrs: 0,
        totalNhrs: 3,
        createdAt: "2024-01-01T00:00:00Z",
      },
      academicSemester: {
        id: 2,
        name: "Second Semester",
        academicYearId: 1,
        startDate: "2025-02-01",
        endDate: "2025-06-30",
        registrationStartDate: "2025-01-15",
        registrationEndDate: "2025-02-15",
        createdAt: "2024-01-01T00:00:00Z",
      },
    },
    student: {
      id: 1,
      studentTempId: 1001,
      userId: 101,
      placeOfBirthTown: "Arba Minch",
      placeOfBirthZone: "Gamo",
      placeOfBirthRegion: "SNNPR",
      dateOfBirth: "2007-03-15",
      addressKebele: "01",
      addressWoreda: "Arba Minch Zuria",
      addressTown: "Arba Minch",
      addressZone: "Gamo",
      addressRegion: "SNNPR",
      phoneHome: "+251911234567",
      phoneOffice: "",
      maritalStatus: "Single",
      departmentId: 1,
      programId: 1,
      admissionTypeId: 1,
      listOfSlip: "2024/2025",
      registrationDate: "2024-09-01",
      profilePicture: null,
      currentStudyingYear: "2024",
      currentStudyingSemester: "Second Semester",
      currentStudyingLevel: "10",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-09-01T00:00:00Z",
      sectionId: 1,
      user: {
        id: 101,
        firstName: "Sarah",
        middleName: "Jane",
        lastName: "Johnson",
        email: "sarah.johnson@student.edu",
        phoneNumber: "+251911234567",
        password: "hashed_password",
        userType: "STUDENT",
        gender: "Female",
        nationality: "Ethiopian",
        userMainId: "GS/2024/001",
      },
    },
  },
  {
    id: 5,
    teachingAssignmentId: 105,
    studentId: 1,
    practical1: 20,
    practical2: 18,
    practical3: 0,
    practical1Type: "Essay",
    practical2Type: "Presentation",
    practical3Type: "Not Applicable",
    totalPractical: 38,
    practicalStatus: "COMPLETED",
    theory: 46,
    theoryStatus: "COMPLETED",
    totalMark: 84,
    gradeInLetter: "A-",
    comment: "Outstanding writing and communication skills",
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    teachingAssignment: {
      id: 105,
      teacherId: 5,
      sectionId: 1,
      courseId: 5,
      academicSemesterId: 2,
      academicYearId: 1,
      level: "10",
      departmentId: 1,
      teacher: {
        id: 5,
        userId: 5,
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-01T00:00:00Z",
      },
      section: {
        id: 1,
        sectionName: "10-A",
        academicYearId: 1,
        createdAt: "2024-01-01T00:00:00Z",
        departmentId: 1,
      },
      course: {
        id: 5,
        collegeId: 1,
        departmentId: 1,
        level: "10",
        courseCode: "ENG-10",
        title: "English Language",
        theoryNhrs: 3,
        practicalNhrs: 1,
        cooperativeNhrs: 0,
        totalNhrs: 4,
        createdAt: "2024-01-01T00:00:00Z",
      },
      academicSemester: {
        id: 2,
        name: "Second Semester",
        academicYearId: 1,
        startDate: "2025-02-01",
        endDate: "2025-06-30",
        registrationStartDate: "2025-01-15",
        registrationEndDate: "2025-02-15",
        createdAt: "2024-01-01T00:00:00Z",
      },
    },
    student: {
      id: 1,
      studentTempId: 1001,
      userId: 101,
      placeOfBirthTown: "Arba Minch",
      placeOfBirthZone: "Gamo",
      placeOfBirthRegion: "SNNPR",
      dateOfBirth: "2007-03-15",
      addressKebele: "01",
      addressWoreda: "Arba Minch Zuria",
      addressTown: "Arba Minch",
      addressZone: "Gamo",
      addressRegion: "SNNPR",
      phoneHome: "+251911234567",
      phoneOffice: "",
      maritalStatus: "Single",
      departmentId: 1,
      programId: 1,
      admissionTypeId: 1,
      listOfSlip: "2024/2025",
      registrationDate: "2024-09-01",
      profilePicture: null,
      currentStudyingYear: "2024",
      currentStudyingSemester: "Second Semester",
      currentStudyingLevel: "10",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-09-01T00:00:00Z",
      sectionId: 1,
      user: {
        id: 101,
        firstName: "Sarah",
        middleName: "Jane",
        lastName: "Johnson",
        email: "sarah.johnson@student.edu",
        phoneNumber: "+251911234567",
        password: "hashed_password",
        userType: "STUDENT",
        gender: "Female",
        nationality: "Ethiopian",
        userMainId: "GS/2024/001",
      },
    },
  },
];

export const getStudentAssessment = async (
  studentId: number
): Promise<StudentAssessment[]> => {
  // Return mock high school assessment data
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log("getStudentAssessment called with studentId:", studentId);
      console.log("Returning mock assessment data:", mockHighSchoolAssessments);
      resolve(mockHighSchoolAssessments);
    }, 300); // Simulate API delay
  });
};
